POTATOES
	The restaurant where Stephen and his brother met for dinner still had the drywall dust in the corners from it's recent construction. 
	They met once a week for dinner, or they tried to, when Stephen first moved to the city, but now it was closer to every other month.
	This restaurant was listed as a top ten new restaurant in the city. The best dish were the lamb chops, per the review Stephen read while he was supposed to be working. They were served with a red wine reduction glaze, and a side of southern style buttery mashed potatoes.
	Typically, their significant others came to dinner with them, Paul's wife and Stephen's girlfriend. This was fine, though Stephen would never admit this, he felt like he was a slightly different person at those dinners, for having her there, or at least, some topics were off limits.
	So tonight, he had expected the conversation to be more interesting, but by the time the food had arrived and they were talking over increasingly dull and few topics. 
	Then when Stephen had just taken a bite, Paul asked him, as if offhandedly, as if this weren't a question he could only ask without their partners: "Whatever happened to Chelsea?" 
	The sound of the conversation, the kitchen, the fans, all echoed on concrete surfaces. The light was garish, and an unnatural white. The lingering chemical scent mixed with garlic and butter from the kitchen, and felt nauseating.
	#
	The summer after Paul graduated, and Stephen completed his Junior year, they went to New Zealand, to work at Mount Hutt as Lifties, and get free season passes. They lived out of the carry on suitcases they brought, not wanting to pay for an extra bag, and not really thinking that they might need more than a few pairs of underwear and a graphic tees.
	Chelsea lived near them, an a town an hour away from the resort where it was cheaper. They would carpool in a beat up Toyota Camry Paul had rented for the summer, their skis running the length down the center of the car. Chelsea rolled joints in the back seat, which they would smoke through the day. Every morning, when they arrived, they each shotgunned exactly one PBR in the parking lot. The beer foam mixed with the parking lot mud, and Stephen felt the crisp mountain air come off the lake, and burn his cheeks.
	Chelsea was every bit the self described bum that Stephen was, but more so. Her Chelsea's clothes were also thrifted. This was a style choice, liking the strange and ill fitting jackets, but also an ethical one. None of them would contribute to the carbon output of the world, or the slave like conditions of sweat shops in Bangladesh. 
	Chelsea washed with one bottle of Dr. Bronner's soap, and didn't wash her hair at all, allowing it, in her words, to retain its natural oils. Her deodorant was a mix of coconut oil and baking soda. She was into crystals, horoscopes, and mindfulness. Chelsea had dropped out of college after one year, which she described, when it came up, as "bullshit," "stuck-up," and "too expensive." Now, she was a full time ski bum, following the winter, and saving just enough money from her work as a ski instructor for her plane ticket to the next destination.
	At a party, midway through the summer, they were on the porch, smoking out of a grimy bowl. The porch was old, unstained wood. Everyone else had gone inside.
	Despite the cold, Chelsea wasn't wearing a jacket.
	They talked for a while, and when Stephen noticed she was shivering, and could see the goosebumps raise her blonde arm hair, he offered her his coat.
	She laughed, took it, and said, "do you want to carry my books home too?"
	And he said, "yea, like an Archie comic."
	And she said "What the fuck is an Archie comic?"
	And he leaned in and kissed her. And she kissed him. And they made out against the railing, and Stephen got really cold, but kept kissing, and didn't want to go inside because he wasn't sure if it would ever happen again.
	Then she must have felt him shivering, and said "come-on lets go inside," and in the party, which was just a bunch of people drinking and talking and eating chips, in a warm, damp living room, he felt like he had gotten away with something. They didn't hold hands. Or kiss again. She didn't sit on his lap. They didn't make meaningful eye contact.
	All that would come later.
	The next morning, Stephen noticed a splinter on the inside of his thumb while cutting a tomato for turkey sandwiches he was preparing for lunch. He must have gotten it while making out and been too drunk, or at least, too distracted, to notice. He tried pulling it out with his fingernails, but couldn't grasp it. So he used the tip of the knife to pry it out, and held a paper towel over the cut, until the bleeding stopped. Over the next few days it got infected, and wound up being a much larger wound.
	When they got back to town, Stephen would get dropped off at Chelsea's place, and then he ended up staying over there place more often than not. She had a tapestry in her room, a dream catcher, photos of her friends - decorations that she said were light enough to travel with, but made wherever she was feel like a home.
	She said, even then, that Stephen seemed uptight, stressed, that he seemed like he was hiding something. 
	The trip that had initially been about Stephen and Paul, gradually became more about Stephen and Chelsea, which Paul almost seemed to welcome. He was increasingly spending his time studying in preperation for his new job. Even though he had the job already, and a degree, all things that Stephen pointed out to him, Paul felt stressed, and underprepared. He stopped going to the parties. After his shift was over, instead of getting some runs in, he went straight back home to study, and Stephen and Chelsea would get a ride home with some other people later.
	Stephen probably could have stopped this, but he didn't really want to.
	At the end of the summer Chelsea and Stephen made plans to see eachother again. Stephen would finish out his last year, then meet Chelsea in Chile, where they would live together, go skiing, and fuck all the time.
	She gave him an amethyst, which she said would relieve his stress and anxiety, and, maybe, to remind him of her.
	#
	They talked to each other every day. Stephen would catch her up on drama with his friends, and what test he was studying for, and Chelsea, who was still in New Zealand, would talk about the life on the mountain.
	Stephen started applying for jobs midway through his first semester back. Before each interview he would thumb the amathyst in his pocket, feeling its grooves. Even though he didn't believe in it's "power," it calmed him down. He landed an internship at a big tech company in Seattle, which he signed and accepted.
	He called Chelsea to tell her. She didn't try and hide her distain. He had "sold out." He was "fake." He was a "liar" for promising to come meet her in Chile the next summer.
	He said it was just a few months and then he would come meet her after that, and if he got a full time offer after the internship he could reconsider then, but for now, it was too good an opportunity to pass up. If he did take the job, he could take every vacation he had to go see her. Or maybe she could move in with him.
	She told him to fuck off.
	Stephen went to the library bathroom, into a stall, and cried. He'd stop when he heard the door open, would wait till the person left, and then cry again.
	Less than a month later he saw a picture of her on Instagram, kissing some dude. They were both wearing ski hims. Chelsea's cheeks were red, and windburnt.
#
	Stephen swallowed, looked at his plate.  It had been years since he'd thought about her.  He ran his fork through his mashed potatoes, drawing lines to the porcelain below. The red wine glaze ran into the channels. 
	Paul lived in the suburbs outside Bellevue, which is outside Seattle. He and his wife had a dog and were expecting a kid, not that his wife was pregnant, but it was in The Plan. His clothes he bought new. His kitchenware was expensive. He kept his wires organized. His ties were sorted by color. He didn't smoke weed, and he preferred nice wine - which he drank at a leisurely pace. They skied together, but not as much. 
	None of this was wrong, but it all had a certain air of inevitability, the way a ball, even as it might bounce around, would inevitably fall into a groove.
	Stephen felt, that even as these things might annoy him, they also annoyed him because they were a reflection of the changes in himself, that he was making all the same transitions. Who, in their almost thirties, wants to live like they did in their early twenties.
	Stephen had been dating the same person for four years, and despite questions from nearly everyone in their file, had yet to set on a plan for an engagement, let a alone a wedding.
	Stephen felt his breath. He noticed seconds.
	He put on a smile, chuckled, and said "I have no idea."
	"You were obsessed with her. I thought you might end up together."
	The couple at the table next to them laughed. They were young, pretty, and Stephen felt an instant of resentment.
	"It was infatuation really." He felt a familiar tension settle over his heart. He loved his girlfriend. She was kind. She cooked well. She was smart, career oriented - like he was. "Besides, we had very different lives. I can't be a ski bum forever. I mean, its fun for a while, but eventually you have to join the real world."
	So what, if, occasionally, he watched the train come in, and pictured himself stepping off the platform. So what, time moved faster now. Maybe its just a part of getting older. Maybe the brain only has so much space in memory for sitting at a desk nine hours a day.
	He took a bite of his mashed potatoes. The potatoes were a little grainy. Could they be instant? Surely not in a restaurant like this. At these prices. With these people around, with these beautiful straight teeth new suits and dazzling smiles demonstrating surely impeccable tastes, someone would have noticed by now.
	"Is something wrong?"
	"Well its just this here, I don't think this is what I wanted. I mean, it was supposed to be really good, and everyone else seems to be enjoying it. I mean, something in this, I don't know seems fake, artificial. I guess it just lacks depth or something. I don't want to make a fuss or anything. It's just, well it doesn't seem to be as good as everyone said it would be. It's just me I guess, maybe I just haven’t developed the taste. It's just a feeling I’m getting."
	He had lost Chelsea's crystal a long time ago. He hadn't thrown it away, but one day he realized he didn't have it anymore. He still had the scar on his thumb, from the splinter, and sometimes he rubbed his knuckles against it, feeling its groove, even though it faded every year.
	He did this, as he took another bite, and tried to enjoy his meal.